export * from "../types/api";
export function readError(res: Response): Promise<string>;
export function createHttpClient(resolveBaseUrl: import("../types/api").BaseUrlResolver): {
  get<T>(path: string): Promise<T>;
  post<T>(path: string, body?: BodyInit | null, init?: RequestInit): Promise<T>;
  put<T>(path: string, body: unknown): Promise<T>;
  del<T>(path: string): Promise<T>;
};
export function createSharedApi(resolveBaseUrl: import("../types/api").BaseUrlResolver): {
  integrationsStatus: () => Promise<import("../types/api").IntegrationsStatus>;
  oauthDisconnect: (provider: string) => Promise<{ status: string; provider: string }>;
  oauthClientSet: (provider: string, payload: { client_id?: string; client_secret?: string }) => Promise<{ status: string; provider: string }>;
  oauthClientClear: (provider: string) => Promise<{ status: string; provider: string }>;
  composioConnect: (toolkit: string) => Promise<{ toolkit: string; redirect_url: string; connection_id?: string | null }>;
  composioDisconnect: (id: string) => Promise<{ status: string; id: string }>;
  composioConfigSet: (payload: { api_key?: string; user_id?: string }) => Promise<{ status: string }>;
  composioConfigClear: () => Promise<{ status: string }>;
  composioToolkits: () => Promise<{ toolkits: import("../types/api").ComposioToolkit[] }>;
  composioToolkitTools: (slug: string) => Promise<{ tools: import("../types/api").ComposioToolSummary[] }>;
  composioRenameConnection: (id: string, alias: string) => Promise<{ status: string; id: string; alias: string }>;
  llmGet: () => Promise<{ effective: import("../types/api").LLMEffective }>;
  llmSet: (payload: { provider?: string; model?: string; temperature?: number; api_key?: string }) => Promise<{ effective: import("../types/api").LLMEffective }>;
  llmClear: () => Promise<{ effective: import("../types/api").LLMEffective }>;
  secretSet: (name: string, value: string) => Promise<{ status: string; name: string }>;
  secretClear: (name: string) => Promise<{ status: string; name: string }>;
  pyjiitSet: (payload: { username?: string; password?: string }) => Promise<{ status: string }>;
  pyjiitClear: () => Promise<{ status: string }>;
  voiceSet: (payload: Partial<import("../types/api").VoiceConfigPublic>) => Promise<{ effective: import("../types/api").VoiceConfigPublic }>;
  voiceClear: () => Promise<{ effective: import("../types/api").VoiceConfigPublic }>;
  deleteSession: (id: string) => Promise<{ status: string; id: string }>;
  debugStats: () => Promise<import("../types/api").DebugStatsResponse>;
  memoryStats: () => Promise<Record<string, unknown>>;
  memoryClaims: (params?: Record<string, string | number | boolean | undefined>) => Promise<Record<string, unknown>>;
  memoryMaintenance: () => Promise<Record<string, unknown>>;
  memoryClear: () => Promise<Record<string, unknown>>;
};
